version: '3.8'

services:
  oscilationbot:
    build: ./
    container_name: oscilationbot
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_CONNECTION_STRING: mysql://root:admin@mysql/alarm_notification
      PORT: 3306
      DATABASE_NAME: alarm_notification
      DB_CONNECTION_STRING_TEST: mysql://root:admin@mysql/alarm_notification_test
      DB_USERNAME: root
      DB_PASSWORD: admin
      DB_HOST: mysql
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet 2G
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
    mem_limit: "1024m"
    healthcheck:
      test:
        [
          "CMD",
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p$$MYSQL_ROOT_PASSWORD'
        ]
      timeout: 20s
      retries: 10
